### ISSUE TITLE
Using winston as a peer dependency

### ISSUE THREAD

**Issue by noamokman** [segment-boneyard/winston-logger#2]
It looks like the version of winston is a dependency here,
Are there any plans to change that so the package doesn't need to update every time winston does?

Maybe to implement it like so:

``` js
var Logger = require('winston-logger')(require('winston'));
```

**Comment by calvinfo** [comment]
Oh totally. I don't think we use this anymore really–happy to take PRs!

**Comment by noamokman** [comment]
Then I'll PR :+1: 
Just out of curiosity, what to you use for logging purposes?

**Comment by calvinfo** [comment]
Sweet! We ended up switching over to segmentio/yal and then wrote plugins
for that.

**Comment by noamokman** [comment]
Irrelevant.. closing
